version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Europe/Paris
    logging:
        driver: none

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - TZ=Europe/Paris
    logging:
        driver: none

  server:
    container_name: dashboard-backend
    build: ./backend
    volumes:
      - ./backend:/backend
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/dashboard
      - REDIS_URI=redis://redis:6379
      - TZ=Europe/Paris
    ports:
      - "8080:8080"
    links:
      - redis
      - mongodb

  frontend:
    container_name: dashboard-frontend
    build: ./frontend
    volumes:
      - ./frontend:/frontend
    environment:
      - REACT_APP_API_URI=http://localhost:8080
    ports:
      - "3000:3000"
    links:
      - backend
